# Site settings
title: an IT starter blog
email: jadianes@gmail.com
author: J. A. Dianes
description: "An IT starter blog"
baseurl: ""
url: "http://www.jadianes.me"
google_analytics:
animated: true

# Build settings
markdown: kramdown
permalink: /:title
paginate: 3
sass:
  compressed: true

