# Site settings
title: An IT solo blog
email: your_email@example.com
author: J. A. Dianes
description: "An IT solo blog"
baseurl: ""
url: "http://pixyll.com"
google_analytics:
animated: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true

