# Site settings
title: An IT solo blog
email: jadianes@gmail.com
author: J. A. Dianes
description: "An IT solo blog"
baseurl: ""
url: "http://www.jadianes.me"
google_analytics:
animated: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true

