# Site settings
title: building Data Products
email: jadianes@gmail.com
author: J. A. Dianes
description: "building Data Products"
baseurl: ""
url: "http://www.jadianes.me"
google_analytics:
animated: true

# Build settings
markdown: kramdown
permalink: /:title
paginate: 3
sass:
  compressed: true

